//! Training session coordinator

use glam::Vec3;
use plix_common::protocol::BotSnapshot;
use plix_common::time::Tick;
use plix_common::types::BotId;

use super::bot::TrainingBot;
use super::config::TrainingConfig;
use super::stats::TrainingStats;

/// Events generated by training coordinator
#[derive(Debug, Clone)]
pub enum TrainingEvent {
    /// Bot respawned at position
    BotRespawned { bot_id: BotId, position: Vec3 },
}

/// Orchestrates training session: bots, stats, reset
#[derive(Debug)]
pub struct TrainingCoordinator {
    /// Training configuration
    pub config: TrainingConfig,
    /// Active training bots
    pub bots: Vec<TrainingBot>,
    /// Session statistics
    pub stats: TrainingStats,
    /// Bot spawn points
    spawn_points: Vec<Vec3>,
}

impl TrainingCoordinator {
    /// Create new coordinator with configuration and spawn points
    pub fn new(config: TrainingConfig, spawn_points: Vec<Vec3>, start_tick: Tick) -> Self {
        let mut coordinator = Self {
            config,
            bots: Vec::new(),
            stats: TrainingStats::new(start_tick),
            spawn_points,
        };
        coordinator.spawn_all_bots();
        coordinator
    }

    /// Spawn all bots at initial positions
    pub fn spawn_all_bots(&mut self) {
        self.bots.clear();
        for i in 0..self.config.bot_count {
            let spawn_idx = i as usize % self.spawn_points.len().max(1);
            let spawn_point = self
                .spawn_points
                .get(spawn_idx)
                .copied()
                .unwrap_or(Vec3::new(0.0, 1.0, 0.0));
            let bot = TrainingBot::new(BotId(i), spawn_point, self.config.bot_behavior);
            self.bots.push(bot);
        }
    }

    /// Tick update - update bot behaviors and check respawns
    pub fn tick(&mut self, current_tick: Tick) -> Vec<TrainingEvent> {
        let mut events = Vec::new();

        for bot in &mut self.bots {
            if bot.is_dead {
                // Check for respawn
                if let Some(respawn_tick) = bot.respawn_tick {
                    if current_tick.0 >= respawn_tick.0 {
                        bot.respawn();
                        events.push(TrainingEvent::BotRespawned {
                            bot_id: bot.id,
                            position: bot.position,
                        });
                    }
                }
            } else {
                // Update behavior (movement)
                bot.update(current_tick);
            }
        }

        events
    }

    /// Record an attack attempt (miss or hit)
    pub fn record_attack(&mut self) {
        self.stats.record_attack();
    }

    /// Process hit on a bot, returns true if bot was killed
    pub fn process_hit(&mut self, bot_id: BotId, damage: u8, current_tick: Tick) -> bool {
        self.stats.record_hit();

        if self.config.invincibility_bots {
            return false; // Hit counted but no damage applied
        }

        if let Some(bot) = self.bots.iter_mut().find(|b| b.id == bot_id) {
            let respawn_tick = Tick(current_tick.0 + self.config.bot_respawn_delay_ticks);
            let killed = bot.take_damage(damage, respawn_tick);
            if killed {
                self.stats.record_kill();
            }
            killed
        } else {
            false
        }
    }

    /// Reset session - respawn all bots, clear stats, return player spawn
    pub fn reset(&mut self, current_tick: Tick) -> Vec3 {
        self.spawn_all_bots();
        self.stats.reset(current_tick);

        // Return first spawn point for player
        self.spawn_points
            .first()
            .copied()
            .unwrap_or(Vec3::new(0.0, 2.0, 0.0))
    }

    /// Get bot states for snapshot replication
    pub fn bot_snapshots(&self) -> Vec<BotSnapshot> {
        self.bots
            .iter()
            .map(|b| BotSnapshot {
                id: b.id,
                position: b.position,
                health: b.health,
                is_dead: b.is_dead,
            })
            .collect()
    }

    /// Get a bot by ID
    pub fn get_bot(&self, bot_id: BotId) -> Option<&TrainingBot> {
        self.bots.iter().find(|b| b.id == bot_id)
    }

    /// Get a mutable bot by ID
    pub fn get_bot_mut(&mut self, bot_id: BotId) -> Option<&mut TrainingBot> {
        self.bots.iter_mut().find(|b| b.id == bot_id)
    }

    /// Get stats reference
    pub fn stats(&self) -> &TrainingStats {
        &self.stats
    }

    /// Check if player should be invincible
    pub fn is_player_invincible(&self) -> bool {
        self.config.invincibility_player
    }

    /// Get player respawn delay in ticks
    pub fn player_respawn_delay_ticks(&self) -> u32 {
        self.config.player_respawn_delay_ticks
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::training::config::BotBehaviorType;

    fn test_spawn_points() -> Vec<Vec3> {
        vec![
            Vec3::new(10.0, 2.0, 10.0),
            Vec3::new(20.0, 2.0, 20.0),
            Vec3::new(30.0, 2.0, 30.0),
        ]
    }

    #[test]
    fn test_coordinator_creation() {
        let config = TrainingConfig::default();
        let spawns = test_spawn_points();
        let coordinator = TrainingCoordinator::new(config, spawns.clone(), Tick(0));

        assert_eq!(coordinator.bots.len(), 5); // default bot_count
        assert_eq!(coordinator.stats.hits, 0);
        assert_eq!(coordinator.spawn_points, spawns);
    }

    #[test]
    fn test_spawn_all_bots() {
        let mut config = TrainingConfig::default();
        config.bot_count = 3;
        let spawns = test_spawn_points();
        let coordinator = TrainingCoordinator::new(config, spawns.clone(), Tick(0));

        assert_eq!(coordinator.bots.len(), 3);
        assert_eq!(coordinator.bots[0].spawn_point, spawns[0]);
        assert_eq!(coordinator.bots[1].spawn_point, spawns[1]);
        assert_eq!(coordinator.bots[2].spawn_point, spawns[2]);
    }

    #[test]
    fn test_spawn_wraps_spawn_points() {
        let mut config = TrainingConfig::default();
        config.bot_count = 5;
        let spawns = vec![Vec3::new(10.0, 2.0, 10.0), Vec3::new(20.0, 2.0, 20.0)];
        let coordinator = TrainingCoordinator::new(config, spawns.clone(), Tick(0));

        assert_eq!(coordinator.bots.len(), 5);
        // Should wrap around spawn points
        assert_eq!(coordinator.bots[0].spawn_point, spawns[0]);
        assert_eq!(coordinator.bots[1].spawn_point, spawns[1]);
        assert_eq!(coordinator.bots[2].spawn_point, spawns[0]);
        assert_eq!(coordinator.bots[3].spawn_point, spawns[1]);
        assert_eq!(coordinator.bots[4].spawn_point, spawns[0]);
    }

    #[test]
    fn test_process_hit_records_stats() {
        let config = TrainingConfig::default();
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns, Tick(0));

        coordinator.process_hit(BotId(0), 30, Tick(100));

        assert_eq!(coordinator.stats.hits, 1);
        assert_eq!(coordinator.stats.kills, 0);

        // Get bot health
        let bot = coordinator.get_bot(BotId(0)).unwrap();
        assert_eq!(bot.health, 70);
    }

    #[test]
    fn test_process_hit_records_kill() {
        let config = TrainingConfig::default();
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns, Tick(0));

        let killed = coordinator.process_hit(BotId(0), 100, Tick(100));

        assert!(killed);
        assert_eq!(coordinator.stats.hits, 1);
        assert_eq!(coordinator.stats.kills, 1);

        let bot = coordinator.get_bot(BotId(0)).unwrap();
        assert!(bot.is_dead);
    }

    #[test]
    fn test_invincible_bot_no_damage() {
        let mut config = TrainingConfig::default();
        config.invincibility_bots = true;
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns, Tick(0));

        let killed = coordinator.process_hit(BotId(0), 100, Tick(100));

        assert!(!killed);
        assert_eq!(coordinator.stats.hits, 1); // Hit still counted
        assert_eq!(coordinator.stats.kills, 0);

        let bot = coordinator.get_bot(BotId(0)).unwrap();
        assert_eq!(bot.health, 100); // No damage
        assert!(!bot.is_dead);
    }

    #[test]
    fn test_bot_respawn_on_tick() {
        let mut config = TrainingConfig::default();
        config.bot_respawn_delay_ticks = 60;
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns, Tick(0));

        // Kill bot at tick 100
        coordinator.process_hit(BotId(0), 100, Tick(100));
        assert!(coordinator.get_bot(BotId(0)).unwrap().is_dead);

        // Tick before respawn - no event
        let events = coordinator.tick(Tick(159));
        assert!(events.is_empty());
        assert!(coordinator.get_bot(BotId(0)).unwrap().is_dead);

        // Tick at respawn time - should respawn
        let events = coordinator.tick(Tick(160));
        assert_eq!(events.len(), 1);
        assert!(!coordinator.get_bot(BotId(0)).unwrap().is_dead);

        let TrainingEvent::BotRespawned { bot_id, .. } = &events[0];
        assert_eq!(*bot_id, BotId(0));
    }

    #[test]
    fn test_reset_clears_stats() {
        let config = TrainingConfig::default();
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns, Tick(0));

        // Accumulate stats
        coordinator.record_attack();
        coordinator.record_attack();
        coordinator.process_hit(BotId(0), 100, Tick(100));

        assert_eq!(coordinator.stats.attacks, 2);
        assert_eq!(coordinator.stats.hits, 1);
        assert_eq!(coordinator.stats.kills, 1);

        // Reset
        coordinator.reset(Tick(500));

        assert_eq!(coordinator.stats.attacks, 0);
        assert_eq!(coordinator.stats.hits, 0);
        assert_eq!(coordinator.stats.kills, 0);
        assert_eq!(coordinator.stats.session_start, Tick(500));
    }

    #[test]
    fn test_reset_respawns_bots() {
        let config = TrainingConfig::default();
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns.clone(), Tick(0));

        // Kill a bot and move others
        coordinator.process_hit(BotId(0), 100, Tick(100));
        coordinator.bots[1].position = Vec3::new(999.0, 999.0, 999.0);

        assert!(coordinator.bots[0].is_dead);

        // Reset
        coordinator.reset(Tick(500));

        // All bots alive at spawn points
        assert!(!coordinator.bots[0].is_dead);
        assert_eq!(coordinator.bots[0].position, spawns[0]);
        assert_eq!(coordinator.bots[1].position, spawns[1]);
    }

    #[test]
    fn test_bot_snapshots() {
        let mut config = TrainingConfig::default();
        config.bot_count = 2;
        let spawns = test_spawn_points();
        let coordinator = TrainingCoordinator::new(config, spawns.clone(), Tick(0));

        let snapshots = coordinator.bot_snapshots();

        assert_eq!(snapshots.len(), 2);
        assert_eq!(snapshots[0].id, BotId(0));
        assert_eq!(snapshots[0].position, spawns[0]);
        assert_eq!(snapshots[0].health, 100);
        assert!(!snapshots[0].is_dead);
    }

    #[test]
    fn test_record_attack() {
        let config = TrainingConfig::default();
        let spawns = test_spawn_points();
        let mut coordinator = TrainingCoordinator::new(config, spawns, Tick(0));

        coordinator.record_attack();
        coordinator.record_attack();
        coordinator.record_attack();

        assert_eq!(coordinator.stats.attacks, 3);
    }

    #[test]
    fn test_dummy_bots_dont_move() {
        let mut config = TrainingConfig::default();
        config.bot_count = 1;
        config.bot_behavior = BotBehaviorType::Dummy;
        let spawns = vec![Vec3::new(10.0, 2.0, 10.0)];
        let mut coordinator = TrainingCoordinator::new(config, spawns.clone(), Tick(0));

        let initial_pos = coordinator.bots[0].position;

        // Run many ticks
        for tick in 0..100 {
            coordinator.tick(Tick(tick));
        }

        assert_eq!(coordinator.bots[0].position, initial_pos);
    }
}
