[package]
name = "plix-common"
description = "Shared types, protocol definitions, and math utilities for Plix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde-big-array = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
noise = "0.9"
toml = { workspace = true }
toml_edit = "0.22"
rand = { workspace = true }
sha2 = "0.10"
chrono = "0.4"
tracing = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = "3.10"
