//! Server browser data types.

use serde::{Deserialize, Serialize};

/// A game server entry in the master server directory.
///
/// This represents a game server that has registered with the master
/// and is available for players to connect to.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ServerEntry {
    /// Unique stable identifier (hash of host:port, generated by master)
    pub server_id: String,
    /// Display name of the server
    pub name: String,
    /// IP address or hostname
    pub host: String,
    /// Game port
    pub port: u16,
    /// Geographic region (e.g., "eu-west", "us-east")
    pub region: String,
    /// Descriptive tags (e.g., ["ctf", "competitive"])
    pub tags: Vec<String>,
    /// Current player count
    pub player_count: u8,
    /// Maximum player capacity
    pub max_players: u8,
    /// Supported game modes
    pub game_modes: Vec<String>,
    /// Protocol version for compatibility filtering
    pub protocol_version: String,
    /// Timestamp of last heartbeat (Unix epoch seconds)
    pub last_seen: u64,
}

/// Response containing list of active servers.
///
/// Returned by the master server's GET /servers endpoint.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerListResponse {
    /// List of active server entries
    pub servers: Vec<ServerEntry>,
    /// Total count (may differ from servers.len() if pagination added later)
    pub total: usize,
    /// Timestamp of response (Unix epoch seconds)
    pub timestamp: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_server_entry_json_roundtrip() {
        let entry = ServerEntry {
            server_id: "abc123def456".to_string(),
            name: "Test Server".to_string(),
            host: "192.168.1.100".to_string(),
            port: 7777,
            region: "eu-west".to_string(),
            tags: vec!["ctf".to_string(), "competitive".to_string()],
            player_count: 12,
            max_players: 32,
            game_modes: vec!["ctf".to_string(), "tdm".to_string()],
            protocol_version: "0.1.0".to_string(),
            last_seen: 1702828800,
        };

        let json = serde_json::to_string(&entry).expect("serialize");
        let deserialized: ServerEntry = serde_json::from_str(&json).expect("deserialize");

        assert_eq!(entry, deserialized);
    }

    #[test]
    fn test_server_entry_json_fields() {
        let entry = ServerEntry {
            server_id: "test_id".to_string(),
            name: "My Server".to_string(),
            host: "127.0.0.1".to_string(),
            port: 8080,
            region: "local".to_string(),
            tags: vec!["test".to_string()],
            player_count: 5,
            max_players: 10,
            game_modes: vec!["ffa".to_string()],
            protocol_version: "1.0.0".to_string(),
            last_seen: 1000,
        };

        let json = serde_json::to_string(&entry).expect("serialize");

        // Verify all expected fields are present
        assert!(json.contains("\"server_id\":\"test_id\""));
        assert!(json.contains("\"name\":\"My Server\""));
        assert!(json.contains("\"host\":\"127.0.0.1\""));
        assert!(json.contains("\"port\":8080"));
        assert!(json.contains("\"region\":\"local\""));
        assert!(json.contains("\"player_count\":5"));
        assert!(json.contains("\"max_players\":10"));
        assert!(json.contains("\"protocol_version\":\"1.0.0\""));
        assert!(json.contains("\"last_seen\":1000"));
    }

    #[test]
    fn test_server_list_response_json_roundtrip() {
        let response = ServerListResponse {
            servers: vec![
                ServerEntry {
                    server_id: "server1".to_string(),
                    name: "Server One".to_string(),
                    host: "192.168.1.1".to_string(),
                    port: 7777,
                    region: "eu".to_string(),
                    tags: vec![],
                    player_count: 0,
                    max_players: 16,
                    game_modes: vec![],
                    protocol_version: "0.1.0".to_string(),
                    last_seen: 1000,
                },
                ServerEntry {
                    server_id: "server2".to_string(),
                    name: "Server Two".to_string(),
                    host: "192.168.1.2".to_string(),
                    port: 7778,
                    region: "us".to_string(),
                    tags: vec!["ranked".to_string()],
                    player_count: 8,
                    max_players: 32,
                    game_modes: vec!["ctf".to_string()],
                    protocol_version: "0.1.0".to_string(),
                    last_seen: 2000,
                },
            ],
            total: 2,
            timestamp: 3000,
        };

        let json = serde_json::to_string(&response).expect("serialize");
        let deserialized: ServerListResponse = serde_json::from_str(&json).expect("deserialize");

        assert_eq!(response.servers.len(), deserialized.servers.len());
        assert_eq!(response.total, deserialized.total);
        assert_eq!(response.timestamp, deserialized.timestamp);
        assert_eq!(response.servers[0], deserialized.servers[0]);
        assert_eq!(response.servers[1], deserialized.servers[1]);
    }

    #[test]
    fn test_empty_server_list_response() {
        let response = ServerListResponse {
            servers: vec![],
            total: 0,
            timestamp: 1000,
        };

        let json = serde_json::to_string(&response).expect("serialize");
        let deserialized: ServerListResponse = serde_json::from_str(&json).expect("deserialize");

        assert!(deserialized.servers.is_empty());
        assert_eq!(deserialized.total, 0);
    }
}
