[package]
name = "plix-server"
description = "Authoritative game server for Plix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "plix-server"
path = "src/main.rs"

[dependencies]
plix-common = { workspace = true }
plix-net = { workspace = true }
plix-arena = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true }
dirs-next = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
tempfile = { workspace = true }
serde_json = { workspace = true }
