//! BR Lite coordinator - orchestrates all BR Lite match components

use std::collections::HashMap;

use glam::{Vec2, Vec3};
use plix_common::time::Tick;
use plix_common::types::PlayerId;
use tracing::{debug, info};

use super::config::BrLiteConfig;
use super::damage::DamageController;
use super::loot::{LootManager, LootType};
use super::state::{BrLiteState, PlayerBrState, ZoneState};
use super::zone::ZoneController;

/// Events generated by the BR Lite coordinator
#[derive(Debug, Clone)]
pub enum BrLiteEvent {
    /// Zone state changed (phase transition or radius update)
    ZoneUpdate(ZoneState),
    /// Player eliminated
    Elimination {
        player_id: PlayerId,
        alive_count: u8,
    },
    /// Match has a winner
    Victory { winner_id: PlayerId },
    /// Player took zone damage
    ZoneDamage { player_id: PlayerId, damage: u32 },
    /// Loot item spawned
    LootSpawn {
        loot_id: u16,
        position: Vec3,
        loot_type: LootType,
    },
    /// Loot item picked up
    LootPickup { loot_id: u16, player_id: PlayerId },
    /// Player healed from health pack
    PlayerHealed {
        player_id: PlayerId,
        heal_amount: u32,
    },
    /// Player received speed boost
    SpeedBoostApplied {
        player_id: PlayerId,
        multiplier: f32,
        duration_ticks: u32,
    },
    /// Player collected scrap resource
    ScrapPickedUp { player_id: PlayerId, quantity: u8 },
}

/// Match phase for lifecycle management
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatchPhase {
    /// Waiting for minimum players
    Lobby,
    /// Match is active
    Playing,
    /// Match ended, showing results
    PostMatch,
}

impl Default for MatchPhase {
    fn default() -> Self {
        MatchPhase::Lobby
    }
}

/// Main coordinator for BR Lite match
#[derive(Debug)]
pub struct BrLiteCoordinator {
    /// Configuration
    config: BrLiteConfig,
    /// Zone controller
    zone_controller: ZoneController,
    /// Damage controller
    damage_controller: DamageController,
    /// Loot manager
    loot_manager: LootManager,
    /// Match state
    state: BrLiteState,
    /// Current match phase
    match_phase: MatchPhase,
    /// Post-match timer (ticks remaining)
    post_match_timer: u32,
    /// Arena size for zone calculations
    arena_size: Vec2,
}

impl BrLiteCoordinator {
    /// Create a new BR Lite coordinator
    pub fn new(config: BrLiteConfig, arena_size: Vec2) -> Self {
        let zone_controller = ZoneController::new(&config, arena_size);
        let damage_controller = DamageController::new(config.damage_tick_interval);
        let bonus_duration_ticks = config.bonus_duration_secs * 60; // Convert to ticks
        let loot_manager = LootManager::new(bonus_duration_ticks);

        Self {
            config,
            zone_controller,
            damage_controller,
            loot_manager,
            state: BrLiteState::new(),
            match_phase: MatchPhase::Lobby,
            post_match_timer: 0,
            arena_size,
        }
    }

    /// Get current match phase
    pub fn match_phase(&self) -> MatchPhase {
        self.match_phase
    }

    /// Get the BR Lite state
    pub fn state(&self) -> &BrLiteState {
        &self.state
    }

    /// Get mutable BR Lite state
    pub fn state_mut(&mut self) -> &mut BrLiteState {
        &mut self.state
    }

    /// Get zone state
    pub fn zone_state(&self) -> &ZoneState {
        &self.state.zone
    }

    /// Get alive player count
    pub fn alive_count(&self) -> usize {
        self.state.alive_count()
    }

    /// Get minimum players required
    pub fn min_players(&self) -> u8 {
        self.config.min_players
    }

    /// Check if a player is alive
    pub fn is_alive(&self, player_id: PlayerId) -> bool {
        self.state.is_alive(player_id)
    }

    /// Get player's BR state
    pub fn get_player_state(&self, player_id: PlayerId) -> Option<&PlayerBrState> {
        self.state.get_player_state(player_id)
    }

    /// Get speed multiplier for a player (from loot effects)
    pub fn get_speed_multiplier(&self, player_id: PlayerId) -> f32 {
        self.loot_manager.get_speed_multiplier(player_id)
    }

    /// Add a player to the match
    pub fn add_player(&mut self, player_id: PlayerId) {
        self.state.add_player(player_id);
        info!(
            target: "br_lite",
            player_id = ?player_id,
            alive_count = self.state.alive_count(),
            "player_joined"
        );
    }

    /// Remove a player from the match (disconnect)
    pub fn remove_player(&mut self, player_id: PlayerId) -> Vec<BrLiteEvent> {
        let mut events = Vec::new();

        if self.match_phase == MatchPhase::Playing && self.state.is_alive(player_id) {
            // Player disconnected during match - eliminate them
            if let Some(winner) = self.state.eliminate(player_id) {
                events.push(BrLiteEvent::Elimination {
                    player_id,
                    alive_count: self.state.alive_count() as u8,
                });
                events.push(BrLiteEvent::Victory { winner_id: winner });
                self.transition_to_post_match();
            } else {
                events.push(BrLiteEvent::Elimination {
                    player_id,
                    alive_count: self.state.alive_count() as u8,
                });
            }
        } else {
            self.state.remove_player(player_id);
        }

        self.loot_manager.clear_effects(player_id);
        self.damage_controller.clear_player(player_id);

        info!(
            target: "br_lite",
            player_id = ?player_id,
            alive_count = self.state.alive_count(),
            "player_removed"
        );

        events
    }

    /// Try to start the match (if enough players)
    pub fn try_start_match(&mut self) -> Option<BrLiteEvent> {
        if self.match_phase != MatchPhase::Lobby {
            return None;
        }

        if self.state.alive_count() < self.config.min_players as usize {
            return None;
        }

        self.start_match()
    }

    /// Force start the match
    pub fn start_match(&mut self) -> Option<BrLiteEvent> {
        if self.match_phase != MatchPhase::Lobby {
            return None;
        }

        // Calculate zone center (arena center or configured)
        let center = self
            .config
            .zone_center
            .map(|c| Vec2::new(c[0], c[1]))
            .unwrap_or_else(|| self.arena_size / 2.0);

        // Initialize zone
        let zone_state = self.zone_controller.init_state(center);
        self.state.zone = zone_state.clone();
        self.state.match_started = true;

        self.match_phase = MatchPhase::Playing;

        info!(
            target: "br_lite",
            player_count = self.state.alive_count(),
            zone_center = ?center,
            zone_radius = self.zone_controller.initial_radius(),
            "match_started"
        );

        Some(BrLiteEvent::ZoneUpdate(zone_state))
    }

    /// Process a tick of the match
    /// Returns events generated this tick
    pub fn tick(
        &mut self,
        current_tick: Tick,
        player_positions: &HashMap<PlayerId, Vec3>,
    ) -> Vec<BrLiteEvent> {
        let mut events = Vec::new();

        match self.match_phase {
            MatchPhase::Lobby => {
                // Nothing to tick in lobby
            }
            MatchPhase::Playing => {
                // Update zone
                if self.zone_controller.tick(&mut self.state.zone) {
                    events.push(BrLiteEvent::ZoneUpdate(self.state.zone.clone()));
                }

                // Process zone damage
                let alive_players: Vec<(PlayerId, Vec3)> = self
                    .state
                    .alive_players
                    .iter()
                    .filter_map(|&id| player_positions.get(&id).map(|&pos| (id, pos)))
                    .collect();

                let damage_result = self.damage_controller.tick_all(
                    alive_players.into_iter(),
                    &self.zone_controller,
                    &self.state.zone,
                    current_tick,
                );

                for (player_id, damage) in damage_result.damaged {
                    events.push(BrLiteEvent::ZoneDamage { player_id, damage });
                }

                // Process loot effects expiration
                self.loot_manager.tick(current_tick);
            }
            MatchPhase::PostMatch => {
                // Count down post-match timer
                if self.post_match_timer > 0 {
                    self.post_match_timer -= 1;
                }
            }
        }

        events
    }

    /// Eliminate a player (from combat death or zone damage)
    pub fn eliminate_player(&mut self, player_id: PlayerId) -> Vec<BrLiteEvent> {
        let mut events = Vec::new();

        if !self.state.is_alive(player_id) {
            return events;
        }

        // Clear effects and damage tracking
        self.loot_manager.clear_effects(player_id);
        self.damage_controller.clear_player(player_id);

        // Eliminate in state
        if let Some(winner) = self.state.eliminate(player_id) {
            events.push(BrLiteEvent::Elimination {
                player_id,
                alive_count: self.state.alive_count() as u8,
            });
            events.push(BrLiteEvent::Victory { winner_id: winner });
            self.transition_to_post_match();
        } else {
            events.push(BrLiteEvent::Elimination {
                player_id,
                alive_count: self.state.alive_count() as u8,
            });
        }

        events
    }

    /// Check loot pickup for a player
    pub fn check_loot_pickup(
        &mut self,
        player_id: PlayerId,
        player_pos: Vec3,
        current_tick: Tick,
    ) -> Vec<BrLiteEvent> {
        let mut events = Vec::new();

        if !self.config.loot_enabled || !self.state.is_alive(player_id) {
            return events;
        }

        // Check for nearby loot
        if let Some(loot_id) = self.loot_manager.check_pickup(player_pos) {
            if let Some(loot_type) = self.loot_manager.try_pickup(loot_id) {
                events.push(BrLiteEvent::LootPickup { loot_id, player_id });

                // Apply effect
                match loot_type {
                    LootType::HealthPack { heal_amount } => {
                        events.push(BrLiteEvent::PlayerHealed {
                            player_id,
                            heal_amount,
                        });

                        debug!(
                            target: "br_lite",
                            player_id = ?player_id,
                            heal_amount,
                            "health_pack_collected"
                        );
                    }
                    LootType::SpeedBoost {
                        multiplier,
                        duration_ticks,
                    } => {
                        self.loot_manager
                            .apply_effect(player_id, loot_type, current_tick);
                        events.push(BrLiteEvent::SpeedBoostApplied {
                            player_id,
                            multiplier,
                            duration_ticks,
                        });

                        debug!(
                            target: "br_lite",
                            player_id = ?player_id,
                            multiplier,
                            duration_ticks,
                            "speed_boost_collected"
                        );
                    }
                    LootType::Scrap { quantity } => {
                        // Scrap goes directly to player inventory
                        // The server main loop will handle adding to hotbar
                        events.push(BrLiteEvent::ScrapPickedUp {
                            player_id,
                            quantity,
                        });

                        debug!(
                            target: "br_lite",
                            player_id = ?player_id,
                            quantity,
                            "scrap_collected"
                        );
                    }
                }
            }
        }

        events
    }

    /// Spawn a loot item
    pub fn spawn_loot(&mut self, position: Vec3, loot_type: LootType) -> BrLiteEvent {
        let loot_id = self.loot_manager.spawn_loot(position, loot_type);

        debug!(
            target: "br_lite",
            loot_id,
            position = ?position,
            "loot_spawned"
        );

        BrLiteEvent::LootSpawn {
            loot_id,
            position,
            loot_type,
        }
    }

    /// Transition to post-match phase
    fn transition_to_post_match(&mut self) {
        self.match_phase = MatchPhase::PostMatch;
        self.post_match_timer = self.config.post_match_delay_secs * 60; // Convert to ticks

        info!(
            target: "br_lite",
            winner = ?self.state.winner,
            total_eliminations = self.state.total_eliminations,
            "match_ended"
        );
    }

    /// Check if post-match timer has expired
    pub fn is_post_match_complete(&self) -> bool {
        self.match_phase == MatchPhase::PostMatch && self.post_match_timer == 0
    }

    /// Reset for a new match
    pub fn reset(&mut self) {
        self.state.reset();
        self.loot_manager.reset();
        self.damage_controller.reset();
        self.zone_controller = ZoneController::new(&self.config, self.arena_size);
        self.match_phase = MatchPhase::Lobby;
        self.post_match_timer = 0;

        info!(target: "br_lite", "coordinator_reset");
    }

    /// Get winner (if match ended)
    pub fn winner(&self) -> Option<PlayerId> {
        self.state.winner
    }

    /// Check if player is inside the safe zone
    pub fn is_in_zone(&self, player_pos: Vec3) -> bool {
        self.zone_controller
            .is_in_zone(player_pos, &self.state.zone)
    }

    /// Get loot items
    pub fn loot_items(&self) -> &[super::loot::LootItem] {
        self.loot_manager.items()
    }

    /// Get debug info
    pub fn debug_info(&self) -> super::state::BrLiteDebugInfo {
        self.state.debug_info()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::br_lite::config::ZonePhase;

    fn test_config() -> BrLiteConfig {
        BrLiteConfig {
            min_players: 2,
            post_match_delay_secs: 5,
            bonus_duration_secs: 10,
            phases: vec![
                ZonePhase::new(10, 5, 0.8, 5),
                ZonePhase::new(10, 5, 0.5, 10),
            ],
            initial_radius: Some(50.0),
            ..Default::default()
        }
    }

    #[test]
    fn test_coordinator_creation() {
        let config = test_config();
        let coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        assert_eq!(coordinator.match_phase(), MatchPhase::Lobby);
        assert_eq!(coordinator.alive_count(), 0);
        assert_eq!(coordinator.min_players(), 2);
    }

    #[test]
    fn test_add_remove_player() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));

        assert_eq!(coordinator.alive_count(), 2);
        assert!(coordinator.is_alive(PlayerId(1)));

        coordinator.remove_player(PlayerId(1));
        assert_eq!(coordinator.alive_count(), 1);
        assert!(!coordinator.is_alive(PlayerId(1)));
    }

    #[test]
    fn test_try_start_match_not_enough_players() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));

        let event = coordinator.try_start_match();
        assert!(event.is_none());
        assert_eq!(coordinator.match_phase(), MatchPhase::Lobby);
    }

    #[test]
    fn test_try_start_match_success() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));

        let event = coordinator.try_start_match();
        assert!(event.is_some());
        assert_eq!(coordinator.match_phase(), MatchPhase::Playing);
    }

    #[test]
    fn test_elimination() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.add_player(PlayerId(3));
        coordinator.start_match();

        let events = coordinator.eliminate_player(PlayerId(3));
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], BrLiteEvent::Elimination { .. }));
        assert_eq!(coordinator.alive_count(), 2);
    }

    #[test]
    fn test_victory() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.start_match();

        let events = coordinator.eliminate_player(PlayerId(2));
        assert_eq!(events.len(), 2);

        // Check for victory event
        let has_victory = events
            .iter()
            .any(|e| matches!(e, BrLiteEvent::Victory { winner_id } if *winner_id == PlayerId(1)));
        assert!(has_victory);

        assert_eq!(coordinator.match_phase(), MatchPhase::PostMatch);
        assert_eq!(coordinator.winner(), Some(PlayerId(1)));
    }

    #[test]
    fn test_zone_update_on_match_start() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));

        let event = coordinator.start_match();
        assert!(matches!(event, Some(BrLiteEvent::ZoneUpdate(_))));
    }

    #[test]
    fn test_loot_spawn_and_pickup() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.start_match();

        // Spawn loot
        let loot_pos = Vec3::new(10.0, 2.0, 10.0);
        let event = coordinator.spawn_loot(loot_pos, LootType::HealthPack { heal_amount: 25 });
        assert!(matches!(event, BrLiteEvent::LootSpawn { .. }));

        // Pickup loot
        let events = coordinator.check_loot_pickup(PlayerId(1), loot_pos, Tick(100));
        assert!(!events.is_empty());
        assert!(events
            .iter()
            .any(|e| matches!(e, BrLiteEvent::LootPickup { .. })));
        assert!(events
            .iter()
            .any(|e| matches!(e, BrLiteEvent::PlayerHealed { .. })));
    }

    #[test]
    fn test_speed_boost_pickup() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.start_match();

        let loot_pos = Vec3::new(10.0, 2.0, 10.0);
        coordinator.spawn_loot(
            loot_pos,
            LootType::SpeedBoost {
                multiplier: 1.5,
                duration_ticks: 600,
            },
        );

        let events = coordinator.check_loot_pickup(PlayerId(1), loot_pos, Tick(100));
        assert!(events
            .iter()
            .any(|e| matches!(e, BrLiteEvent::SpeedBoostApplied { .. })));

        assert_eq!(coordinator.get_speed_multiplier(PlayerId(1)), 1.5);
    }

    #[test]
    fn test_reset() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.start_match();
        coordinator.eliminate_player(PlayerId(2));

        coordinator.reset();

        assert_eq!(coordinator.match_phase(), MatchPhase::Lobby);
        assert_eq!(coordinator.alive_count(), 0);
        assert!(coordinator.winner().is_none());
    }

    #[test]
    fn test_post_match_complete() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.start_match();
        coordinator.eliminate_player(PlayerId(2));

        assert_eq!(coordinator.match_phase(), MatchPhase::PostMatch);
        assert!(!coordinator.is_post_match_complete());

        // Tick through post-match
        let positions = HashMap::new();
        for _ in 0..(5 * 60) {
            // 5 seconds at 60Hz
            coordinator.tick(Tick(0), &positions);
        }

        assert!(coordinator.is_post_match_complete());
    }

    #[test]
    fn test_is_in_zone() {
        let config = test_config();
        let mut coordinator = BrLiteCoordinator::new(config, Vec2::new(64.0, 64.0));

        coordinator.add_player(PlayerId(1));
        coordinator.add_player(PlayerId(2));
        coordinator.start_match();

        // Center should be arena center (32, 32)
        assert!(coordinator.is_in_zone(Vec3::new(32.0, 5.0, 32.0)));
        assert!(!coordinator.is_in_zone(Vec3::new(200.0, 5.0, 200.0)));
    }
}
